server:
  port: 6083

spring:
  application:
    name: mango-producer
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        serviceName: ${spring.application.name}
  boot:
    admin:
      client:
        url: http://localhost:6082

management:
  endpoints:
    web:
      expose:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS