server:
  port: 6020

spring:
  application:
    name: mango-config
  profiles:
    active: native
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        serviceName: ${spring.application.name}
    config:
#      label: master
      server:
#        git:
#          uri: https://.git
#          search-paths: mango-config-repo
#          username: aa
#          password: aa
        native:
          search-locations: classpath:config
  boot:
    admin:
      client:
        url: http://localhost:6082
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS

feign:
  hystrix:
    enabled: true
