server:
  port: 6090

spring:
  application:
    name: mango-zuul
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        serviceName: ${spring.application.name}
  boot:
    admin:
      client:
        url: http://localhost:6082

management:
  endpoints:
    web:
      expose:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS

zuul:
  routes:
    ribbon:
      path: /ribbon/**
      serviceId: mango-consumer
    feign:
      path: /feign/**
      serviceId: mango-consumer