server:
  port: 6081

spring:
  application:
    name: mango-backup
  boot:
    admin:
      client:
        url: http://localhost:6082
mango:
  backup:
    datasource:
      host: localhost
      username: root
      password: 123456
      database: mango
management:
  endpoints:
    web:
      expose:
        include: "*"