server:
  port: 6082

spring:
  application:
    name: mango-monitor
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        serviceName: ${spring.application.name}

management:
  endpoints:
    web:
      expose:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS